### ISSUE TITLE
[Help]How to check the single IPv6 address valid.

### ISSUE THREAD

**Issue by wangchong2023** [seancfoley/IPAddress#109]
I use the function 'isIPv6Address' to test whether '2001:0D88:0:CD30:123:4567:89AB:CDEF' is a valid single IPv6  address.
But the test failed, can you help me to fix whether something is wrong for usage of IPAddressStringParameters.
This function  'isIPv6Address' is used to check validation of some single IP address case, such as administration address, etc.

```
public static boolean isIPv6Address(String ipAddrStr) {
        IPAddressStringParameters strParams = new IPAddressStringParameters.Builder().
                allowPrefixOnly(false).
                allowSingleSegment(false).
                getIPv6AddressParametersBuilder().
                allow_mixed_inet_aton(false).
                allowBase85(false).
                allowLeadingZeros(false).
                allowMixed(false).
                allowPrefixesBeyondAddressSize(false).
                allowPrefixLengthLeadingZeros(false).
                allowUnlimitedLeadingZeros(false).
                allowWildcardedSeparator(false).
                allowZone(false).
                getParentBuilder().
                allowIPv4(false).
                allowEmpty(false).
                allowWildcardedSeparator(false).
                allowPrefix(false).setRangeOptions(AddressStringParameters.RangeParameters.NO_RANGE).
                allow_inet_aton(false).
                allowMask(false).
                allow_inet_aton(false).toParams();

        return checkHostIdentifierString(new IPAddressString(ipAddrStr, strParams));
    }
  
@Test
public void testIPv6Address() {
    assertTrue(isIPv6Address("2001:0D88:0:CD30:123:4567:89AB:CDEF"));
}
```

**Comment by seancfoley** [comment]
Use IPAddress.toAddress() and check the exception.
```
Exception in thread "main" inet.ipaddr.AddressStringException: 2001:0D88:0:CD30:123:4567:89AB:CDEF IP Address error: segment value starts with zero
	at inet.ipaddr.format.validate.Validator.validateAddress(Validator.java:1398)
	at inet.ipaddr.format.validate.Validator.validateIPAddress(Validator.java:164)
	at inet.ipaddr.format.validate.Validator.validateIPAddressStr(Validator.java:142)
	at inet.ipaddr.IPAddressString.validate(IPAddressString.java:531)
	at inet.ipaddr.IPAddressString.validate(IPAddressString.java:480)
	at inet.ipaddr.IPAddressString.toAddress(IPAddressString.java:1042)
	at issue109.Issue.isIPv6Address(Issue.java:41)
	at issue109.Issue.main(Issue.java:16)
```
Remove`allowLeadingZeros(false)`
