### ISSUE TITLE
Missing requirement "inet.ipaddr"

### ISSUE THREAD

**Issue by TelecomCoder** [seancfoley/IPAddress#12]
Hi, my maven project builds fine after importing your libraries. But when running, the bundle is not able to launch due to errors. Any tips here? 
My imports:
```
import inet.ipaddr.IPAddress;
import inet.ipaddr.IPAddressString;
```

Example of how i used it (if i remove this line, everything works fine):
`public IPAddress global_net = new IPAddressString("192.168.0.1/24").getAddress();
`

Already added below dependency to pom.xml.
```
<dependency>
        <groupId>com.github.seancfoley</groupId>
        <artifactId>ipaddress</artifactId>
        <version>5.0.0</version>
</dependency>
```
Error:
> Could not start bundle mvn:com.intel.rsd.onos/main/1.0-SNAPSHOT in feature(s) main-1.0-SNAPSHOT: Unresolved constraint in bundle com.intel.rsd.onos.main [221]: Unable to resolve 221.0: missing requirement [221.0] osgi.wiring.package; (osgi.wiring.package=inet.ipaddr)
	at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:403)
	at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:371)
	at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:349)
	at Proxy31184b0b_27d3_4cd4_87ac_ea2d42dceecb.installFeature(Unknown Source)
	at org.onosproject.app.impl.ApplicationManager.installAppFeatures(ApplicationManager.java:283)
	at org.onosproject.app.impl.ApplicationManager.access$200(ApplicationManager.java:66)
	at org.onosproject.app.impl.ApplicationManager$InternalStoreDelegate.notify(ApplicationManager.java:210)
	at org.onosproject.app.impl.ApplicationManager$InternalStoreDelegate.notify(ApplicationManager.java:202)
	at org.onosproject.store.AbstractStore.notifyDelegate(AbstractStore.java:58)[142:org.onosproject.onos-api:1.15.0.SNAPSHOT]
	at org.onosproject.store.app.DistributedApplicationStore.access$800(DistributedApplicationStore.java:99)[146:org.onosproject.onos-core-dist:1.15.0.SNAPSHOT]
	at org.onosproject.store.app.DistributedApplicationStore$AppActivator.accept(DistributedApplicationStore.java:530)[146:org.onosproject.onos-core-dist:1.15.0.SNAPSHOT]
	at org.onosproject.store.app.DistributedApplicationStore$AppActivator.accept(DistributedApplicationStore.java:523)[146:org.onosproject.onos-core-dist:1.15.0.SNAPSHOT]
	at org.onosproject.store.atomix.primitives.impl.AtomixDistributedTopic.lambda$null$0(AtomixDistributedTopic.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_191] >

**Comment by seancfoley** [comment]
Hello, it looks to me like something to do with osgi, which is a framework for packaging and module organization that is separate from both maven and from ipaddress.
osgi maintains its own set of files for managing dependencies.  It looks like you use apache karaf for managing the osgi dependencies.
To me it looks like you need to make changes to your apache karaf and/or osgi configurations to allow it to load ipaddress at runtime.
I've just done a bit of googling, maybe these links can help:
https://karaf.apache.org/manual/latest/#_creating_bundles
https://karaf.apache.org/manual/latest-2.x/developers-guide/creating-bundles.html
Seems you need to wrap ipaddress into a bundle somehow.
